# Generated by Django 6.1.1 on 2026-10-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_DB',
            fields=[
                ('Veh_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Veh_Name', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=10)),
                ('Dob', models.DateField()),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
